# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exercise2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 411)
        self.Leg = QtWidgets.QLabel(Form)
        self.Leg.setGeometry(QtCore.QRect(0, 0, 681, 411))
        self.Leg.setText("")
        self.Leg.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/LegMovement/LegMove0001.png"))
        self.Leg.setObjectName("Leg")
        self.Home_button = QtWidgets.QLabel(Form)
        self.Home_button.setGeometry(QtCore.QRect(20, 370, 86, 31))
        self.Home_button.setMouseTracking(True)
        self.Home_button.setText("")
        self.Home_button.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/HomearrowleftAsset 3.png"))
        self.Home_button.setObjectName("Home_button")
        self.Target = QtWidgets.QLabel(Form)
        self.Target.setGeometry(QtCore.QRect(100, 230, 100, 100))
        self.Target.setText("")
        self.Target.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Target/Target0001.png"))
        self.Target.setObjectName("Target")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(500, 380, 160, 19))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(500, 350, 160, 19))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(135)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.Ex_complete = QtWidgets.QLabel(Form)
        self.Ex_complete.setGeometry(QtCore.QRect(160, 440, 331, 201))
        self.Ex_complete.setMouseTracking(True)
        self.Ex_complete.setText("")
        self.Ex_complete.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/ExCompleteAsset 2.png"))
        self.Ex_complete.setObjectName("Ex_complete")
        self.Targetsmall = QtWidgets.QLabel(Form)
        self.Targetsmall.setGeometry(QtCore.QRect(640, 10, 30, 30))
        self.Targetsmall.setText("")
        self.Targetsmall.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall.setObjectName("Targetsmall")
        self.Targetsmall_2 = QtWidgets.QLabel(Form)
        self.Targetsmall_2.setGeometry(QtCore.QRect(640, 40, 30, 30))
        self.Targetsmall_2.setText("")
        self.Targetsmall_2.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_2.setObjectName("Targetsmall_2")
        self.Targetsmall_3 = QtWidgets.QLabel(Form)
        self.Targetsmall_3.setGeometry(QtCore.QRect(640, 70, 30, 30))
        self.Targetsmall_3.setText("")
        self.Targetsmall_3.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_3.setObjectName("Targetsmall_3")
        self.Targetsmall_4 = QtWidgets.QLabel(Form)
        self.Targetsmall_4.setGeometry(QtCore.QRect(640, 100, 30, 30))
        self.Targetsmall_4.setText("")
        self.Targetsmall_4.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_4.setObjectName("Targetsmall_4")
        self.Targetsmall_5 = QtWidgets.QLabel(Form)
        self.Targetsmall_5.setGeometry(QtCore.QRect(640, 190, 30, 30))
        self.Targetsmall_5.setText("")
        self.Targetsmall_5.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_5.setObjectName("Targetsmall_5")
        self.Targetsmall_6 = QtWidgets.QLabel(Form)
        self.Targetsmall_6.setGeometry(QtCore.QRect(640, 130, 30, 30))
        self.Targetsmall_6.setText("")
        self.Targetsmall_6.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_6.setObjectName("Targetsmall_6")
        self.Targetsmall_7 = QtWidgets.QLabel(Form)
        self.Targetsmall_7.setGeometry(QtCore.QRect(640, 160, 30, 30))
        self.Targetsmall_7.setText("")
        self.Targetsmall_7.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_7.setObjectName("Targetsmall_7")
        self.Targetsmall_8 = QtWidgets.QLabel(Form)
        self.Targetsmall_8.setGeometry(QtCore.QRect(640, 220, 30, 30))
        self.Targetsmall_8.setText("")
        self.Targetsmall_8.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_8.setObjectName("Targetsmall_8")
        self.Targetsmall_9 = QtWidgets.QLabel(Form)
        self.Targetsmall_9.setGeometry(QtCore.QRect(640, 250, 30, 30))
        self.Targetsmall_9.setText("")
        self.Targetsmall_9.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_9.setObjectName("Targetsmall_9")
        self.Targetsmall_10 = QtWidgets.QLabel(Form)
        self.Targetsmall_10.setGeometry(QtCore.QRect(640, 280, 30, 30))
        self.Targetsmall_10.setText("")
        self.Targetsmall_10.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Targetlogoblank.png"))
        self.Targetsmall_10.setObjectName("Targetsmall_10")
        self.Current_angle_header = QtWidgets.QLabel(Form)
        self.Current_angle_header.setGeometry(QtCore.QRect(240, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Current_angle_header.setFont(font)
        self.Current_angle_header.setObjectName("Current_angle_header")
        self.deg1 = QtWidgets.QLabel(Form)
        self.deg1.setGeometry(QtCore.QRect(380, 10, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.deg1.setFont(font)
        self.deg1.setObjectName("deg1")
        self.Current_angle = QtWidgets.QLabel(Form)
        self.Current_angle.setGeometry(QtCore.QRect(340, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Current_angle.setFont(font)
        self.Current_angle.setObjectName("Current_angle")
        self.deg2 = QtWidgets.QLabel(Form)
        self.deg2.setGeometry(QtCore.QRect(560, 10, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.deg2.setFont(font)
        self.deg2.setObjectName("deg2")
        self.Target_angle_header = QtWidgets.QLabel(Form)
        self.Target_angle_header.setGeometry(QtCore.QRect(420, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Target_angle_header.setFont(font)
        self.Target_angle_header.setObjectName("Target_angle_header")
        self.Target_angle = QtWidgets.QLabel(Form)
        self.Target_angle.setGeometry(QtCore.QRect(520, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Target_angle.setFont(font)
        self.Target_angle.setObjectName("Target_angle")
        self.Leg_warning = QtWidgets.QLabel(Form)
        self.Leg_warning.setGeometry(QtCore.QRect(1000, 1000, 221, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 96, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 96, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Leg_warning.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Leg_warning.setFont(font)
        self.Leg_warning.setObjectName("Leg_warning")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Current_angle_header.setText(_translate("Form", "Current:"))
        self.deg1.setText(_translate("Form", "°"))
        self.Current_angle.setText(_translate("Form", "90"))
        self.deg2.setText(_translate("Form", "°"))
        self.Target_angle_header.setText(_translate("Form", "Target:"))
        self.Target_angle.setText(_translate("Form", "90"))
        self.Leg_warning.setText(_translate("Form", "Keep your upper leg flat!"))

