# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exercise3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 411)
        self.Last_angle = QtWidgets.QLabel(Form)
        self.Last_angle.setGeometry(QtCore.QRect(310, 120, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad CAD")
        font.setPointSize(12)
        self.Last_angle.setFont(font)
        self.Last_angle.setObjectName("Last_angle")
        self.Star_1 = QtWidgets.QLabel(Form)
        self.Star_1.setGeometry(QtCore.QRect(320, 20, 71, 71))
        self.Star_1.setText("")
        self.Star_1.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Star_largeAsset 1.png"))
        self.Star_1.setObjectName("Star_1")
        self.Progreamme_progression_header = QtWidgets.QLabel(Form)
        self.Progreamme_progression_header.setGeometry(QtCore.QRect(20, 60, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Office Symbol Semilight")
        font.setPointSize(16)
        self.Progreamme_progression_header.setFont(font)
        self.Progreamme_progression_header.setTextFormat(QtCore.Qt.AutoText)
        self.Progreamme_progression_header.setObjectName("Progreamme_progression_header")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 100, 271, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.comment = QtWidgets.QLabel(Form)
        self.comment.setGeometry(QtCore.QRect(310, 180, 281, 121))
        self.comment.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.comment.setObjectName("comment")
        self.Progreamme_progression_header_2 = QtWidgets.QLabel(Form)
        self.Progreamme_progression_header_2.setGeometry(QtCore.QRect(310, 140, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS Office Symbol Semilight")
        font.setPointSize(20)
        self.Progreamme_progression_header_2.setFont(font)
        self.Progreamme_progression_header_2.setTextFormat(QtCore.Qt.AutoText)
        self.Progreamme_progression_header_2.setObjectName("Progreamme_progression_header_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Small_flower_1 = QtWidgets.QLabel(Form)
        self.Small_flower_1.setGeometry(QtCore.QRect(-30, 270, 91, 131))
        self.Small_flower_1.setText("")
        self.Small_flower_1.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_1.setOpenExternalLinks(False)
        self.Small_flower_1.setObjectName("Small_flower_1")
        self.Small_flower_2 = QtWidgets.QLabel(Form)
        self.Small_flower_2.setGeometry(QtCore.QRect(20, 270, 91, 131))
        self.Small_flower_2.setText("")
        self.Small_flower_2.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_2.setOpenExternalLinks(False)
        self.Small_flower_2.setObjectName("Small_flower_2")
        self.Small_flower_3 = QtWidgets.QLabel(Form)
        self.Small_flower_3.setGeometry(QtCore.QRect(70, 270, 91, 131))
        self.Small_flower_3.setText("")
        self.Small_flower_3.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_3.setOpenExternalLinks(False)
        self.Small_flower_3.setObjectName("Small_flower_3")
        self.Small_flower_4 = QtWidgets.QLabel(Form)
        self.Small_flower_4.setGeometry(QtCore.QRect(120, 270, 91, 131))
        self.Small_flower_4.setText("")
        self.Small_flower_4.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_4.setOpenExternalLinks(False)
        self.Small_flower_4.setObjectName("Small_flower_4")
        self.Small_flower_5 = QtWidgets.QLabel(Form)
        self.Small_flower_5.setGeometry(QtCore.QRect(170, 270, 91, 131))
        self.Small_flower_5.setText("")
        self.Small_flower_5.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_5.setOpenExternalLinks(False)
        self.Small_flower_5.setObjectName("Small_flower_5")
        self.Small_flower_6 = QtWidgets.QLabel(Form)
        self.Small_flower_6.setGeometry(QtCore.QRect(120, 130, 91, 131))
        self.Small_flower_6.setText("")
        self.Small_flower_6.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_6.setOpenExternalLinks(False)
        self.Small_flower_6.setObjectName("Small_flower_6")
        self.Small_flower_7 = QtWidgets.QLabel(Form)
        self.Small_flower_7.setGeometry(QtCore.QRect(-30, 130, 91, 131))
        self.Small_flower_7.setText("")
        self.Small_flower_7.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_7.setOpenExternalLinks(False)
        self.Small_flower_7.setObjectName("Small_flower_7")
        self.Small_flower_8 = QtWidgets.QLabel(Form)
        self.Small_flower_8.setGeometry(QtCore.QRect(170, 130, 91, 131))
        self.Small_flower_8.setText("")
        self.Small_flower_8.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_8.setOpenExternalLinks(False)
        self.Small_flower_8.setObjectName("Small_flower_8")
        self.Small_flower_9 = QtWidgets.QLabel(Form)
        self.Small_flower_9.setGeometry(QtCore.QRect(20, 130, 91, 131))
        self.Small_flower_9.setText("")
        self.Small_flower_9.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_9.setOpenExternalLinks(False)
        self.Small_flower_9.setObjectName("Small_flower_9")
        self.Small_flower_10 = QtWidgets.QLabel(Form)
        self.Small_flower_10.setGeometry(QtCore.QRect(70, 130, 91, 131))
        self.Small_flower_10.setText("")
        self.Small_flower_10.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowingSmall/AnimationFlowersSmall0001.png"))
        self.Small_flower_10.setOpenExternalLinks(False)
        self.Small_flower_10.setObjectName("Small_flower_10")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(530, 360, 91, 31))
        self.saveButton.setObjectName("saveButton")
        self.Star_2 = QtWidgets.QLabel(Form)
        self.Star_2.setGeometry(QtCore.QRect(450, 20, 71, 71))
        self.Star_2.setText("")
        self.Star_2.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Star_largeAsset 1.png"))
        self.Star_2.setObjectName("Star_2")
        self.Star_3 = QtWidgets.QLabel(Form)
        self.Star_3.setGeometry(QtCore.QRect(580, 20, 71, 71))
        self.Star_3.setText("")
        self.Star_3.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/Star_largeAsset 1.png"))
        self.Star_3.setObjectName("Star_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Last_angle.setText(_translate("Form", "0 degrees"))
        self.Progreamme_progression_header.setText(_translate("Form", "Programme Progression:"))
        self.comment.setText(_translate("Form", "Type your comment here..."))
        self.Progreamme_progression_header_2.setText(_translate("Form", "How did you find the exercise?"))
        self.label_2.setText(_translate("Form", "Well Done!"))
        self.saveButton.setText(_translate("Form", "Save"))

