# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exercise1new.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 411)
        self.Flower = QtWidgets.QLabel(Form)
        self.Flower.setGeometry(QtCore.QRect(0, 0, 681, 411))
        self.Flower.setText("")
        self.Flower.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/FlowerGrowing/AnimationFlowers0001.png"))
        self.Flower.setObjectName("Flower")
        self.Can = QtWidgets.QLabel(Form)
        self.Can.setGeometry(QtCore.QRect(0, 0, 681, 411))
        self.Can.setText("")
        self.Can.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/WateringCan/Can0001.png"))
        self.Can.setObjectName("Can")
        self.Flower_small_1 = QtWidgets.QLabel(Form)
        self.Flower_small_1.setGeometry(QtCore.QRect(640, 10, 31, 30))
        self.Flower_small_1.setText("")
        self.Flower_small_1.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_1.setObjectName("Flower_small_1")
        self.Home_button = QtWidgets.QLabel(Form)
        self.Home_button.setGeometry(QtCore.QRect(20, 360, 91, 41))
        self.Home_button.setMouseTracking(True)
        self.Home_button.setText("")
        self.Home_button.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/HomearrowleftAsset 3.png"))
        self.Home_button.setObjectName("Home_button")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(150, 380, 160, 19))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(150, 350, 160, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.Flower_small_2 = QtWidgets.QLabel(Form)
        self.Flower_small_2.setGeometry(QtCore.QRect(640, 50, 31, 30))
        self.Flower_small_2.setText("")
        self.Flower_small_2.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_2.setObjectName("Flower_small_2")
        self.Flower_small_3 = QtWidgets.QLabel(Form)
        self.Flower_small_3.setGeometry(QtCore.QRect(640, 90, 31, 30))
        self.Flower_small_3.setText("")
        self.Flower_small_3.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_3.setObjectName("Flower_small_3")
        self.Flower_small_4 = QtWidgets.QLabel(Form)
        self.Flower_small_4.setGeometry(QtCore.QRect(640, 130, 31, 30))
        self.Flower_small_4.setText("")
        self.Flower_small_4.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_4.setObjectName("Flower_small_4")
        self.Flower_small_5 = QtWidgets.QLabel(Form)
        self.Flower_small_5.setGeometry(QtCore.QRect(640, 170, 31, 30))
        self.Flower_small_5.setText("")
        self.Flower_small_5.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_5.setObjectName("Flower_small_5")
        self.Flower_small_6 = QtWidgets.QLabel(Form)
        self.Flower_small_6.setGeometry(QtCore.QRect(640, 210, 31, 30))
        self.Flower_small_6.setText("")
        self.Flower_small_6.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_6.setObjectName("Flower_small_6")
        self.Flower_small_7 = QtWidgets.QLabel(Form)
        self.Flower_small_7.setGeometry(QtCore.QRect(640, 250, 31, 30))
        self.Flower_small_7.setText("")
        self.Flower_small_7.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_7.setObjectName("Flower_small_7")
        self.Flower_small_8 = QtWidgets.QLabel(Form)
        self.Flower_small_8.setGeometry(QtCore.QRect(640, 290, 31, 30))
        self.Flower_small_8.setText("")
        self.Flower_small_8.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_8.setObjectName("Flower_small_8")
        self.Flower_small_9 = QtWidgets.QLabel(Form)
        self.Flower_small_9.setGeometry(QtCore.QRect(640, 330, 31, 30))
        self.Flower_small_9.setText("")
        self.Flower_small_9.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_9.setObjectName("Flower_small_9")
        self.Flower_small_10 = QtWidgets.QLabel(Form)
        self.Flower_small_10.setGeometry(QtCore.QRect(640, 370, 31, 30))
        self.Flower_small_10.setText("")
        self.Flower_small_10.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerSymbolOFFAsset 3.png"))
        self.Flower_small_10.setObjectName("Flower_small_10")
        self.Flower_outline = QtWidgets.QLabel(Form)
        self.Flower_outline.setGeometry(QtCore.QRect(0, 0, 681, 411))
        self.Flower_outline.setText("")
        self.Flower_outline.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/FlowerOutline.png"))
        self.Flower_outline.setObjectName("Flower_outline")
        self.Ex_complete = QtWidgets.QLabel(Form)
        self.Ex_complete.setGeometry(QtCore.QRect(490, 500, 331, 201))
        self.Ex_complete.setMouseTracking(True)
        self.Ex_complete.setText("")
        self.Ex_complete.setPixmap(QtGui.QPixmap("../../../../Work/HCARD/Images/Assets/ExCompleteAsset 2.png"))
        self.Ex_complete.setObjectName("Ex_complete")
        self.Target_angle = QtWidgets.QLabel(Form)
        self.Target_angle.setGeometry(QtCore.QRect(110, 310, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Target_angle.setFont(font)
        self.Target_angle.setObjectName("Target_angle")
        self.deg2 = QtWidgets.QLabel(Form)
        self.deg2.setGeometry(QtCore.QRect(150, 300, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.deg2.setFont(font)
        self.deg2.setObjectName("deg2")
        self.deg1 = QtWidgets.QLabel(Form)
        self.deg1.setGeometry(QtCore.QRect(150, 250, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.deg1.setFont(font)
        self.deg1.setObjectName("deg1")
        self.Current_angle = QtWidgets.QLabel(Form)
        self.Current_angle.setGeometry(QtCore.QRect(110, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Current_angle.setFont(font)
        self.Current_angle.setObjectName("Current_angle")
        self.Current_angle_header = QtWidgets.QLabel(Form)
        self.Current_angle_header.setGeometry(QtCore.QRect(10, 260, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Current_angle_header.setFont(font)
        self.Current_angle_header.setObjectName("Current_angle_header")
        self.Target_angle_header = QtWidgets.QLabel(Form)
        self.Target_angle_header.setGeometry(QtCore.QRect(10, 310, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Target_angle_header.setFont(font)
        self.Target_angle_header.setObjectName("Target_angle_header")
        self.Flower_outline.raise_()
        self.Flower.raise_()
        self.Can.raise_()
        self.Flower_small_1.raise_()
        self.Home_button.raise_()
        self.horizontalSlider_2.raise_()
        self.horizontalSlider.raise_()
        self.Flower_small_2.raise_()
        self.Flower_small_3.raise_()
        self.Flower_small_4.raise_()
        self.Flower_small_5.raise_()
        self.Flower_small_6.raise_()
        self.Flower_small_7.raise_()
        self.Flower_small_8.raise_()
        self.Flower_small_9.raise_()
        self.Flower_small_10.raise_()
        self.Ex_complete.raise_()
        self.Target_angle.raise_()
        self.deg2.raise_()
        self.deg1.raise_()
        self.Current_angle.raise_()
        self.Current_angle_header.raise_()
        self.Target_angle_header.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Target_angle.setText(_translate("Form", "90"))
        self.deg2.setText(_translate("Form", "°"))
        self.deg1.setText(_translate("Form", "°"))
        self.Current_angle.setText(_translate("Form", "90"))
        self.Current_angle_header.setText(_translate("Form", "Current:"))
        self.Target_angle_header.setText(_translate("Form", "Target:"))

